from .base import AbstractMetric as AbstractMetric, DivergenceRegistry as DivergenceRegistry

def get(name: str) -> AbstractMetric: ...
def list_metrics() -> list: ...
def register(name: str, metric: AbstractMetric): ...
