import abc
import numpy as np
from abc import ABC, abstractmethod

class AbstractMetric(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def compute(self, a: np.ndarray, b: np.ndarray) -> float: ...
    @abstractmethod
    def geometry_type(self) -> str: ...
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def speed_field(self, grid_size: int) -> np.ndarray: ...

class DivergenceRegistry:
    def __init__(self) -> None: ...
    def register(self, name: str, metric: AbstractMetric) -> None: ...
    def get(self, name: str) -> AbstractMetric: ...
    def available(self) -> list: ...
