import numpy as np
from _typeshed import Incomplete
from kaft.geometry.base import AbstractMetric as AbstractMetric

class EuclideanMetric(AbstractMetric):
    def compute(self, a: np.ndarray, b: np.ndarray) -> float: ...
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def geometry_type(self) -> str: ...

class MinkowskiMetric(AbstractMetric):
    c: Incomplete
    def __init__(self, c: float = 0.6) -> None: ...
    def compute(self, a: np.ndarray, b: np.ndarray) -> float: ...
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def speed_field(self, grid_size: int) -> np.ndarray: ...
    def geometry_type(self) -> str: ...

class GaussianCurvedMetric(AbstractMetric):
    curvature_strength: Incomplete
    width: Incomplete
    def __init__(self, curvature_strength: float = 0.85, width: float = 0.25) -> None: ...
    def compute(self, a: np.ndarray, b: np.ndarray) -> float: ...
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def speed_field(self, grid_size: int) -> np.ndarray: ...
    def geometry_type(self) -> str: ...
