import abc
import numpy as np
from _typeshed import Incomplete
from kaft.geometry.base import AbstractMetric as AbstractMetric

class EuclideanMetric(AbstractMetric, metaclass=abc.ABCMeta):
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def geometry_type(self) -> str: ...

class GaussianCurvedMetric(AbstractMetric, metaclass=abc.ABCMeta):
    curvature_strength: Incomplete
    width: Incomplete
    def __init__(self, curvature_strength: float = 0.85, width: float = 0.25) -> None: ...
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def speed_field(self, grid_size: int) -> np.ndarray: ...
    def geometry_type(self) -> str: ...

class MinkowskiMetric(AbstractMetric, metaclass=abc.ABCMeta):
    c: Incomplete
    def __init__(self, c: float = 0.6) -> None: ...
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def speed_field(self, grid_size: int) -> np.ndarray: ...
    def geometry_type(self) -> str: ...

class FisherRaoMetric(AbstractMetric, metaclass=abc.ABCMeta):
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def speed_field(self, grid_size: int) -> np.ndarray: ...
    def geometry_type(self) -> str: ...

class KLDivergence(AbstractMetric, metaclass=abc.ABCMeta):
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def speed_field(self, grid_size: int) -> np.ndarray: ...
    def geometry_type(self) -> str: ...

class JensenShannonMetric(AbstractMetric, metaclass=abc.ABCMeta):
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def speed_field(self, grid_size: int) -> np.ndarray: ...
    def geometry_type(self) -> str: ...

class AlphaDivergence(AbstractMetric, metaclass=abc.ABCMeta):
    alpha: Incomplete
    def __init__(self, alpha: float = 0.0) -> None: ...
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def speed_field(self, grid_size: int) -> np.ndarray: ...
    def geometry_type(self) -> str: ...
    def __init__(self) -> None: ...
    def register(self, name: str, metric_cls: Type[AbstractMetric]) -> None: ...
    def get(self, name: str) -> AbstractMetric: ...
    def available(self) -> list: ...
