import numpy as np
from _typeshed import Incomplete
from kaft.geometry.base import AbstractMetric as AbstractMetric

class FisherRaoMetric(AbstractMetric):
    def compute(self, a: np.ndarray, b: np.ndarray) -> float: ...
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def speed_field(self, grid_size: int) -> np.ndarray: ...
    def geometry_type(self) -> str: ...

class KLDivergence(AbstractMetric):
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def compute(self, a: np.ndarray, b: np.ndarray) -> float: ...
    def speed_field(self, grid_size: int) -> np.ndarray: ...
    def geometry_type(self) -> str: ...

class JensenShannonMetric(AbstractMetric):
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def compute(self, a: np.ndarray, b: np.ndarray) -> float: ...
    def speed_field(self, grid_size: int) -> np.ndarray: ...
    def geometry_type(self) -> str: ...

class AlphaDivergence(AbstractMetric):
    alpha: Incomplete
    def __init__(self, alpha: float = 0.0) -> None: ...
    def distances(self, vectors: np.ndarray) -> np.ndarray: ...
    def compute(self, a: np.ndarray, b: np.ndarray) -> float: ...
    def speed_field(self, grid_size: int) -> np.ndarray: ...
    def geometry_type(self) -> str: ...

class BregmanDivergence(AbstractMetric):
    F: Incomplete
    grad_F: Incomplete
    hess_F: Incomplete
    def __init__(self, F, grad_F, hess_F=None, name: str = 'bregman') -> None: ...
    def compute(self, p: np.ndarray, q: np.ndarray) -> float: ...
    def speed_field(self, grid: np.ndarray) -> np.ndarray: ...
    def geometry_type(self) -> str: ...

def bregman_kl() -> BregmanDivergence: ...
def bregman_tsallis(q: float) -> BregmanDivergence: ...
def bregman_euclidean() -> BregmanDivergence: ...
def bregman_itakura_saito() -> BregmanDivergence: ...

class WassersteinMetric(AbstractMetric):
    p: Incomplete
    def __init__(self, p: int = 2) -> None: ...
    def compute(self, a: np.ndarray, b: np.ndarray, x_support=None, y_support=None) -> float: ...
    def geometry_type(self): ...
