import numpy as np
from _typeshed import Incomplete
from kaft.dynamics.kstate import KDensity as KDensity

class JordanBoundary:
    k_density: Incomplete
    threshold: Incomplete
    def __init__(self, k_density: KDensity, threshold: float = 0.35) -> None: ...
    def detect(self) -> list[dict]: ...
    @property
    def boundaries(self) -> list[dict]: ...
    def crossing_allowed(self, from_idx: int, to_idx: int, accumulated_energy: float) -> bool: ...

class JordanNoise:
    sigma: Incomplete
    rng: Incomplete
    def __init__(self, sigma: float = 0.05, rng: np.random.Generator | None = None) -> None: ...
    def sample(self, k_density: np.ndarray) -> np.ndarray: ...
    def sample_with_boundary_suppression(self, k_density: np.ndarray, boundary: JordanBoundary) -> np.ndarray: ...
