import numpy as np
from _typeshed import Incomplete
from kaft.geometry.base import AbstractMetric as AbstractMetric

PHASE_THRESHOLDS: dict[str, tuple[float, float]]
SOLITON_LOCK_THRESHOLD: float
SOLITON_LOCK_STEPS: int

class KDensity:
    embeddings: Incomplete
    metric: Incomplete
    epsilon: Incomplete
    def __init__(self, embeddings: np.ndarray, metric: AbstractMetric, epsilon: float = 1e-06) -> None: ...
    def compute(self) -> np.ndarray: ...
    @property
    def density(self) -> np.ndarray: ...
    @property
    def distances(self) -> np.ndarray: ...
    def invalidate(self) -> None: ...

class KState:
    def __init__(self) -> None: ...
    def update(self, density: np.ndarray) -> float: ...
    @property
    def K(self) -> float: ...
    @property
    def phase(self) -> str: ...
    @property
    def soliton_locked(self) -> bool: ...
    @property
    def history(self) -> list[float]: ...
    @property
    def delta_K(self) -> float: ...
