import numpy as np
from _typeshed import Incomplete
from kaft.dynamics.kstate import KDensity as KDensity

class MetricEvolution:
    temperature: Incomplete
    base_step: Incomplete
    def __init__(self, temperature: float = 1.0, base_step: float = 0.1) -> None: ...
    def step(self, k_density_obj: KDensity, k_field: np.ndarray) -> None: ...
    def distribution(self, k_field: np.ndarray) -> np.ndarray: ...
    @property
    def step_count(self) -> int: ...
