import numpy as np
from _typeshed import Incomplete
from kaft.dynamics.kstate import KDensity as KDensity

class FisherRaoGradient:
    k_neighbors: Incomplete
    def __init__(self, k_neighbors: int | None = None) -> None: ...
    def compute(self, embeddings: np.ndarray, k_density: np.ndarray, distances: np.ndarray) -> np.ndarray: ...
    def magnitude(self, field: np.ndarray) -> np.ndarray: ...

class ParallelTransport:
    def __init__(self) -> None: ...
    def to_attractor(self, embeddings: np.ndarray, field: np.ndarray, k_density: np.ndarray) -> tuple[np.ndarray, int]: ...
    def to_point(self, embeddings: np.ndarray, field: np.ndarray, target: np.ndarray) -> np.ndarray: ...

class KAFTTerm2:
    grad: Incomplete
    transport: Incomplete
    def __init__(self, k_neighbors: int | None = None) -> None: ...
    def compute(self, k_density_obj: KDensity) -> np.ndarray: ...
