import numpy as np
from dataclasses import dataclass

@dataclass
class Embedder:
    model_name: str = ...
    def __post_init__(self) -> None: ...
    def encode(self, texts: list[str], *, batch_size: int = 64) -> np.ndarray: ...
    @property
    def dim(self) -> int: ...
