from _typeshed import Incomplete
from dataclasses import dataclass

@dataclass(frozen=True)
class SimulationCrucible:
    domain_label: str
    metric_name: str
    corpus_path: str
    v_cog: float = ...
    temperature: float = ...
    sigma: float = ...
    boundary_threshold: float = ...
    n_waypoints: int = ...
    seed: int = ...
    def __post_init__(self) -> None: ...

ARXIV_KAFT: Incomplete
ARXIV_EUCLIDEAN: Incomplete
