import matplotlib.pyplot as plt
import numpy as np
from _typeshed import Incomplete
from kaft.simulate.runner import Frame as Frame

KAFT_COLOR: str
SOFTMAX_COLOR: str
LOCK_COLOR: str
PHASE_COLORS: Incomplete
PHASE_LABELS: Incomplete

class SimulationVisualiser:
    log: Incomplete
    domain_label: Incomplete
    def __init__(self, log: list[Frame], domain_label: str = 'Simulation') -> None: ...
    def plot_k_evolution(self, ax: plt.Axes | None = None, save_path: str | None = None) -> tuple[plt.Figure, plt.Axes]: ...
    def plot_topology_map(self, embeddings: np.ndarray, records: list[dict], umap_reducer=None, source_idx: int = 0, target_idx: int = -1, metric=None, save_path: str | None = None) -> tuple[plt.Figure, plt.Axes]: ...
    def plot_variance(self, ax: plt.Axes | None = None, save_path: str | None = None) -> tuple[plt.Figure, plt.Axes]: ...
    def plot_k_distributions(self, frame_idx: int = -1, ax: plt.Axes | None = None, save_path: str | None = None) -> tuple[plt.Figure, plt.Axes]: ...
    def plot_divergence(self, ax: plt.Axes | None = None, save_path: str | None = None) -> tuple[plt.Figure, plt.Axes]: ...
    def summary(self, save_path: str | None = None) -> tuple[plt.Figure, np.ndarray]: ...
